config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :users
  resources :todos

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :user_id, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true

  has_many :todos, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "Log in Successfull"
        redirect_to user
      else
        flash.now[:danger] = "Login Error.."
        render 'new'
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You are logged out"
    redirect_to root_path
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  
    def new
      @todo = Todo.new
      #@todo = Todo.paginate(page: params[:page], per_page: 5)
    end
    
    def create
      @todo = Todo.new(todo_params)
      @todo.user = current_user
      if @todo.save
        flash[:success] = "Todo was successfully created"
        redirect_to todo_path(@todo)
      else
        flash[:danger] ="Nope... Try it again"
        render 'new'
      end
    end
    
    def show
      
    end
    
    def edit
      
    end
    
    def update
      if @todo.update(todo_params)
        flash[:success] = "Todo was successfully Updated"
        redirect_to todo_path(@todo)
      else
        flash[:danger] = "That didn't work well! try again..."
        render 'edit'
      end
    end
    
    def index
      @todos = Todo.all
    end
    
    def destroy
      @todo.destroy
      flash[:success] = "Todo was deleted Successfully"
      redirect_to todos_path
    end
    
    private
    
    def set_todo
      @todo = Todo.find(params[:id])
    end
    
    def todo_params
      params.require(:todo).permit(:name, :description)
    
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  #before_action :require_user, except: [:root]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash.now[:success] = "Profile has been created"
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "Oops that didnt work! Lets try that again..."
      render 'new'
    end
    
  end
  
  def show
    @user =  User.find(params[:id])
  end
  
  def edit
    @user =  User.find(params[:id])
  end
  
  def update
    @user =  User.find(params[:id])
    if @user.update(user_params)
      flash.now[:success] = "Your Details have been updated"
    redirect_to user_path(@user)
    else
    render 'edit'
    end
  end
  
  def destroy
      @user =  User.find(params[:id])
      @user.destroy
      session[:user_id] = nil #New add here
      flash.now[:success] = "User was Deleted"
      redirect_to root_path
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, 
                                 :password_confirmation)
  end
  
  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own chef account"
      redirect_to user_path
    end
  end
  
  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin users can perform this action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          </button>
          <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to current_user.name if logged_in? %></li>
            <!-- <li class="divider"></li> -->
          </ul>
         
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create a To Do", new_todo_path %></li>
            <li><%= link_to "To Do List", todos_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Log Out", login_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "log in", login_path %></li>
            <% end %>
          </ul> 
          </div>
        </nav>
      </div>
    
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodosWithActionMailer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>To Do List..</h1>
</div>


<div class="well">
 <h4 class="text center home-text">Hello and welcome to the To Do app. This is just like a Chores list 
 you create at home where you can add a chore and delete it once its done Give it a try!!</h4>
</div>

<div class="container">
    <div>
      <p><%= link_to "Create a Todo", new_todo_path, class: "btn btn-default btn-lg fancy" %>
      <%= link_to "Create a Profile", new_user_path, class: "btn btn-default btn-lg fancy pull-right" %></p>
    </div>
</div>

app/views/todos/_errors.html.erb
<% if @todo.errors.any? %>
 <div class="row">
  <div class="col-md-8 col-md-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
    <h2 class="panel-title">
      <%= pluralize(@todo.errors.count, "error") %> prohibited this <%= @todo.class %> from being saved: <!-- Solution from recipes_test_rb 46 -->
     </h2>
      <div class="panel-body">
       <ul>
        <% @todo.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
     </ul>
    </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/todos/_form.html.erb
<div class="row">
  <div class="col-md-12">
          <%= form_for(@todo, :html => {class: "form-horizontal", role: "form"}) do |f| %>
          
           <div class="form-group">
             <div class="control-label col-md-2">
                <%= f.label :name %> 
             </div>
             <div class="col-md-8">
               <%= f.text_field :name, class: 'form-control', placeholder: "Name of todo", autofocus: true %>
             </div>
           </div>
          
          <div class="form-group">
             <div class="control-label col-md-2">
                <%= f.label :description %> 
             </div>
             <div class="col-md-8">
               <%= f.text_area :description, rows: 5, class: 'form-control', placeholder: "Add todo description" %>
             </div>
           </div>
          
          <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
              <%= f.submit class: "btn btn-primary" %> 
              <%= link_to "Back to Index", todos_path, class: "btn btn-warning" %>
            </div>
          </div>
        
        <% end %>
      </p>
  </div>
</div>

app/views/todos/edit.html.erb
<div class="row">
  <h2 class="text-center">Edit your To Do</h2>
</div>

<%= render "todos/errors" %>

<%= render "todos/form" %>

app/views/todos/index.html.erb
<div class="container">
  <div align="center">
</div>
  <div class="row">
    <h1 class="text-center">To Do List</h1>
    <div class="col-md-8 col-md-offset-2">
        <p>
          <%= link_to "Create a To Do", new_todo_path, class: "btn btn-success" %>
        </p>
          <table class="row">
            <tr>
              <th>Name</th>
              <th class="spacer">gkdgdkdgklbkLJDGLK</th>
              <th>Description</th>
            </tr>
            <% @todos.each do |todo| %>
              <tr class ="well profile-black-white-thin row <%= cycle('profile-black-white-thin-b', '') %>"> 
                <td class="texties"><%= todo.name %></td>
                <td class="texties"><%= todo.description %></td>
                <td><%= link_to "View", todo_path(todo), class: "btn btn-info bttn" %></td>
                <% if logged_in? && current_user == todo.user %>
                  <td><%= link_to "Edit", edit_todo_path(todo), class: "btn btn-warning bttn" %></td>
                  <td><%= link_to "Delete", todo_path(todo), method: :delete, data: {confirm: "Are you sure??"}, class: "btn btn-danger bttn" %></td>
                <% end %>
              </tr>
            <% end %>
          </table>
      </div>
  </div>
</div>

app/views/todos/new.html.erb
<div class="row">
  <h2 class="text-center new-page-text">Create an New To do</h2>
</div>

<% render "todos/errors" %>
<%= render "todos/form" %>

app/views/todos/show.html.erb
<% render "todos/errors" %>

<div class="container">
  <div class="row">
    <h2 class="text-center">My To Do</h2>
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <p><span class="descriptionText">Name:</span> <%= @todo.name %></p>
          <br />
          <p><span class="descriptionText">Description:</span> <%= @todo.description %></p>
           <p>
            <%= link_to "Edit This To Do", edit_todo_path(@todo), class: "btn btn-primary" %> 
            <%= link_to "Back to Index", todos_path, class: "btn btn-warning" %>
          </p>
      </div>
    </div>
</div>
</div>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
 <div class="row">
  <div class="col-md-8 col-md-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
    <h2 class="panel-title">
      <%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.class %> from being saved: <!-- Solution from recipes_test_rb 46 -->
     </h2>
      <div class="panel-body">
       <ul>
        <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
     </ul>
    </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/users/_userform.html.erb
<div class="row">
  <div class="col-md-12">
          <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
           <div class="form-group">
             <div class="control-label col-md-2">
                <%= f.label :name %> 
             </div>
             <div class="col-md-8">
               <%= f.text_field :name, class: 'form-control', placeholder: "Name", autofocus: true %>
             </div>
           </div>
          
          <div class="form-group">
             <div class="control-label col-md-2">
                <%= f.label :email %> 
             </div>
             <div class="col-md-8">
               <%= f.email_field :email, class: 'form-control', placeholder: "Enter your e-mail address" %>
             </div>
           </div>
           
            <div class="form-group">
             <div class="control-label col-md-2">
                <%= f.label :password %> 
             </div>
             <div class="col-md-8">
               <%= f.password_field :password, class: 'form-control', placeholder: "Create a Password..." %>
             </div>
           </div>
           
            <div class="form-group">
             <div class="control-label col-md-2">
                <%= f.label :password_confirmation %> 
             </div>
             <div class="col-md-8">
               <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Please re-enter your password.." %>
             </div>
           </div>
          
          <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
              <%= f.submit "Create your profile", class: "btn btn-primary" %> 
              <%= link_to "Back to Home Page", root_path, class: "btn btn-primary" %> 
            </div>
          </div>
          
        <% end %>
      </p>
   
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <h2 class="text-center new-page-text">Edit your profile</h2>
</div>

<%= render "users/errors" %>
<%= render "users/userform" %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h1 align="center">Users</h1>
    <h3 align="center">I am: <%#= @user.name %> <%#= "(Admin)" if current_user.admin? %></h3>
    <div align="center">
        <p>
            <%= link_to "Create a To Do", new_todo_path, class: "btn btn-success" %>
            <%#= link_to "log Out", login_path, method: :delete, class: "btn btn-danger fancy" %>
            <%= link_to "Todo List", todos_path, class: "btn btn-primary" %>
            <%#= link_to "My Profile", user_path(@user), class: "btn btn-warning" %>
        </p>
          <div align="center">
            
            <% @users.each do |user| %>
             <div class ="col-md-4 col-md-offset-4 well profile-black-white-thin row" <%#= cycle('profile-black-white-thin-b well-grad', '') %> > 
                <p class="descriptionText">Name: <%= user.name %></p>
                <p>Email: <%= user.email %></p>
              <%# if logged_in? && current_user.admin? && !user.admin?  %>
                <p><%#= link_to "Destroy Me", user_path(user), method: :delete,  data: {confirm: "Are you sure??"},  class: "btn btn-danger" %></p>
              <%# end %>
              </div>
            <% end %>
          
        </div>
      </div>
    </div>
  </div>

app/views/users/new.html.erb
<div class="row">
  <h2 class="text-center new-page-text">Create your profile</h2>
</div>

<%= render "users/errors" %>
<%= render "users/userform" %>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
      <h2 class="text-center">My Profile <%= @user.name %></h2>
        <div class="col-md-6 col-md-offset-3">
          <div class="well">
            <p><span class="descriptionText">Name:</span> <%= @user.name %></p>
              <br />
              <p><span class="descriptionText">Email:</span> <%= @user.email %></p>
              <% if @user.todos.count != 0 %>
                <p><span class="descriptionText">Todos:</span> <%= @user.todos.count %></p>
              <% else %>
                <h4>You don't have any Todos yet..</h4>
              <% end %>
               <p>
                 <%= link_to "Create a To do", new_todo_path, class: "btn btn-success" %>
                 <%= link_to "Todo List", todos_path, class: "btn btn-warning" %>
                    <td><%= link_to "Edit", edit_user_path(current_user), class: "btn btn-primary bttn" %></td>
                <%# if logged_in? && current_user.admin? && !@user.admin? %>
                <% if logged_in? %>
                    <td><%= link_to "Delete Me", user_path(current_user), method: :delete, data: {confirm: "Are you sure??"}, 
                                                                        class: "btn btn-danger bttn" %></td>
                <% end %>
              </p>
          </div>
        </div>
    </div>
</div>